### ISSUE TITLE
Error when running presenterm-export --version

### ISSUE THREAD

**Issue by GV14982** [mfontanini/presenterm-export#13]
When I try to run `presenterm-export --version` I get the following error:
```
Traceback (most recent call last):
  File "/Users/gvqz/.local/share/mise/installs/python/3.13.0/bin/presenterm-export", line 5, in <module>
    from presenterm_export.cli import main
  File "/Users/gvqz/.local/share/mise/installs/python/3.13.0/lib/python3.13/site-packages/presenterm_export/cli.py", line 8, in <module>
    from dataclass_wizard import JSONWizard
  File "/Users/gvqz/.local/share/mise/installs/python/3.13.0/lib/python3.13/site-packages/dataclass_wizard/__init__.py", line 100, in <module>
    from .bases_meta import LoadMeta, DumpMeta
  File "/Users/gvqz/.local/share/mise/installs/python/3.13.0/lib/python3.13/site-packages/dataclass_wizard/bases_meta.py", line 10, in <module>
    from .abstractions import AbstractJSONWizard
  File "/Users/gvqz/.local/share/mise/installs/python/3.13.0/lib/python3.13/site-packages/dataclass_wizard/abstractions.py", line 14, in <module>
    from .models import Extras
  File "/Users/gvqz/.local/share/mise/installs/python/3.13.0/lib/python3.13/site-packages/dataclass_wizard/models.py", line 3, in <module>
    from dataclasses import MISSING, Field, _create_fn
ImportError: cannot import name '_create_fn' from 'dataclasses' (/Users/gvqz/.local/share/mise/installs/python/3.13.0/lib/python3.13/dataclasses.py)
```
- OS: MacOS v15.0.1
- Python: v3.13.0
- WeasyPrint: v62.3

I use [mise](https://mise.jdx.dev/) to manage my tool versions, not sure if that has anything to do with it.

**Comment by GV14982** [comment]
Hm, I fixed this by using python version 3.9.
